version: "3.2"

services:

  kafka-producer:
    image: kafka-producer
    build:
        context: kafka-producer
        dockerfile: Dockerfile
    container_name: kafka-producer
    restart: always
    ports:
      - 8280:8080
    environment: 
      - kafka.bootstrap-servers=kafka:9092

  kafka-consumer:
    image: kafka-consumer
    build:
        context: kafka-consumer
        dockerfile: Dockerfile
    container_name: kafka-consumer
    restart: always
    ports:
      - 8380:8080
    environment: 
      - kafka.bootstrap-servers=kafka:9092      
    
networks:
  default:
    external:
      name: playground-network