version: "3.2"

services:
  prometheus:
    image: mrmyiagi/playground-prometheus
    container_name: monitoring-prometheus
    build:
      context: Prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on: 
      - alertmanager

  alertmanager:
    image: prom/alertmanager
    container_name: monitoring-alertmanager
    volumes:
      - ./Prometheus-Alertmanager/data:/data
      - ./Prometheus-Alertmanager/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    restart: unless-stopped

  grafana:
    image: mrmyiagi/playground-grafana
    container_name: monitoring-grafana
    build:
      context: Grafana
      dockerfile: Dockerfile
    environment:
      PrometheusUrl: ${PROMETHEUS_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  default:
    external:
      name: playground-network