version: '3'

services:
  sentry-monitoring:
    image: mrmyiagi/sentry-monitoring
    build:
      context: .
    environment:
      SENTRY_BASE_URL: http://sentry:9000
    ports:
      - "3002:3002"
    
networks:
  default:
    external:
      name: playground-network