{
 "title": "Playground Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka",
   "type": "singlestat",
   "description": "Current status of Kafka. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_brokers{instance=\"kafka-exporter:9308\",job=\"KafkaExporter\"}  "
    }
   ]
  },
  {
   "title": "Kibana",
   "type": "singlestat",
   "description": "Current status of Kibana. ",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kibana_status{instance=\"kibana:5601\",job=\"KibanaExporter\"} "
    }
   ]
  },
  {
   "title": "Elastic Search",
   "type": "singlestat",
   "description": "Current status of Elastic Search. ",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_up{instance=\"elasticsearch_exporter:9114\",job=\"ElasticSearchExporter\"} "
    }
   ]
  },
  {
   "title": "Logstash",
   "type": "singlestat",
   "description": "Current status of Logstash. ",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "logstash_up{instance=\"logstash_exporter:9304\",job=\"LogstashExporter\"}\t"
    }
   ]
  },
  {
   "title": "Sentry ",
   "type": "singlestat",
   "description": "Current status of Sentry. ",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SENTRY_AVAILABILITY{instance=\"sentry-exporter:3002\",job=\"SentryExporter\"}"
    }
   ]
  },
  {
   "title": "Matomo Tracker API",
   "type": "singlestat",
   "description": "Current status of Matomo Tracker API Endpoint.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "matomo_tracker_api_availability_up{instance=\"matomo-exporter:8080\",job=\"MatomoExporter\"}"
    }
   ]
  },
  {
   "title": "Kafka Exporter",
   "type": "singlestat",
   "description": "Current status of Kafka Exporter. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"kafka-exporter:9308\",job=\"KafkaExporter\"}\t"
    }
   ]
  },
  {
   "title": "Kafka Exporter",
   "type": "singlestat",
   "description": "Current status of Kafka Exporter. ",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"kafka-exporter:9308\",job=\"KafkaExporter\"}\t"
    }
   ]
  },
  {
   "title": "Elastic Search Exporter",
   "type": "singlestat",
   "description": "Current status of Elastic Search Exporter. ",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"elasticsearch_exporter:9114\",job=\"ElasticSearchExporter\"}\t"
    }
   ]
  },
  {
   "title": "Logstash Exporter",
   "type": "singlestat",
   "description": "Current status of Logstash Exporter. ",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"logstash_exporter:9304\",job=\"LogstashExporter\"}\t"
    }
   ]
  },
  {
   "title": "Sentry Exporter",
   "type": "singlestat",
   "description": "Current status of Sentry Exporter. ",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"sentry-exporter:3002\",job=\"SentryExporter\"}\t"
    }
   ]
  },
  {
   "title": "Matomo Reporting API",
   "type": "singlestat",
   "description": "Current status of Matomo Reporting API Endpoint.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "matomo_reporting_api_availability_up{instance=\"matomo-exporter:8080\",job=\"MatomoExporter\"}\t"
    }
   ]
  },
  {
   "title": "Matomo Exporter",
   "type": "singlestat",
   "description": "Current status of Matomo Exporter.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"matomo-exporter:8080\",job=\"MatomoExporter\"}\t"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Producer",
   "type": "singlestat",
   "description": "Current status of the Kafka Producer. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"kafka-producer:8080\",job=\"KafkaProducer\"}\t"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "singlestat",
   "description": "Current status of the NGINX Container for Angular Frontend. ",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"playapp:9145\",job=\"Playappfrontend\"}"
    }
   ]
  },
  {
   "title": "Status of all application services",
   "type": "graph",
   "description": "Overview of status for all services used by our application.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"kafka-producer:8080\",job=\"KafkaProducer\"}\t",
     "legendFormat": "Kafka-Producer"
    },
    {
     "expr": "up{instance=\"kafka-consumer:8080\",job=\"KafkaConsumer\"}\t",
     "legendFormat": "Kafka-Consumer"
    },
    {
     "expr": "up{instance=\"playapp:9145\",job=\"Playappfrontend\"}",
     "legendFormat": "Frontend"
    },
    {
     "expr": "watchdog_availability_up{instance=\"kafka-consumer:8080\",job=\"KafkaConsumer\"}\t",
     "legendFormat": "Watchdog"
    }
   ]
  },
  {
   "title": "Consumer",
   "type": "singlestat",
   "description": "Current status of the Kafka Consumer. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"kafka-consumer:8080\",job=\"KafkaConsumer\"}\t"
    }
   ]
  },
  {
   "title": "Watchdog",
   "type": "singlestat",
   "description": "Current status of the Watchdog. Watchdog investigates performance and error status. ",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "watchdog_availability_up{instance=\"kafka-consumer:8080\",job=\"KafkaConsumer\"}\t"
    }
   ]
  },
  {
   "title": "Kafka Producer Message Counter",
   "type": "graph",
   "description": "Overview of sent messages by Kafka Producer during runtime.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(producer_message_playapp_counter_total{instance=\"kafka-producer:8080\",job=\"KafkaProducer\"}) + sum(producer_message_monitoring_counter_total{instance=\"kafka-producer:8080\",job=\"KafkaProducer\"})",
     "legendFormat": "Total amount of messages"
    },
    {
     "expr": "producer_message_playapp_counter_total{instance=\"kafka-producer:8080\",job=\"KafkaProducer\"}",
     "legendFormat": "Messages sent for Websockets"
    },
    {
     "expr": "producer_message_monitoring_counter_total{instance=\"kafka-producer:8080\",job=\"KafkaProducer\"}",
     "legendFormat": "Messages sent for Watchdog"
    }
   ]
  },
  {
   "title": "Kafka Consumer Message Counter",
   "type": "graph",
   "description": "Overview of consumed messages by Kafka Consumer during runtime.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(producer_message_playapp_counter_total{instance=\"kafka-producer:8080\",job=\"KafkaProducer\"}) + sum(consumer_message_monitoring_counter_total{instance=\"kafka-consumer:8080\",job=\"KafkaConsumer\"}\t)",
     "legendFormat": "Total amount of messages"
    },
    {
     "expr": "consumer_message_playapp_counter_total{instance=\"kafka-consumer:8080\",job=\"KafkaConsumer\"}\t",
     "legendFormat": "Messages consumed for Websockets"
    },
    {
     "expr": "consumer_message_monitoring_counter_total{instance=\"kafka-consumer:8080\",job=\"KafkaConsumer\"}\t",
     "legendFormat": "Messages consumed for Watchdog"
    }
   ]
  },
  {
   "title": "Frontend HTTP 40X Responses",
   "type": "graph",
   "description": "Overview of 40X responses of Angular frontend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_requests_total{host=\"playapp\",instance=\"playapp:9145\",job=\"Playappfrontend\",status=~\"40*\"}\t"
    }
   ]
  },
  {
   "title": "Frontend HTTP 50X Responses",
   "type": "graph",
   "description": "Overview of 50X responses of Angular frontend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_requests_total{host=\"playapp\",instance=\"playapp:9145\",job=\"Playappfrontend\",status=~\"50*\"}\t"
    }
   ]
  }
 ]
}