apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  selector:
    app: {{ template "name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.deployment.port }}
    targetPort: {{ .Values.deployment.port }}