revisionHistoryLimit: 0

sentry:
  token: *auth_token*
  baseUrl: http://sentry:9000/
  projects: *list_of_project_strings*

image:
  registry: mswedevmsa.azurecr.io
  name: sentry-monitoring
  version: latest
  imagePullPolicy: Always

deployment:
  replicas: 1
  port: 80
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1

# ingress can be enabled for debugging
ingress:
  enabled: false
  host: sentry-monitoring.dev.azure.company.net