version: '2.1'

services:
  zookeeper:
    image: zookeeper:3.4.10
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:3.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    depends_on:
      - zookeeper


networks:
  default:
    external:
      name: playground-network