version: "3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb    
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - TZ=America/Denver
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=test
      - MATOMO_DATABASE_DBNAME=matomo


  app:
    image: mrmyiagi/matomo
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: matomo    
    restart: always
    volumes:
      - matomo:/var/www/html
      - ./config:/var/www/html/config:rw
      - ./apache2.conf:/etc/apache2/apache2.conf:ro      
#     - ./logs:/var/www/html/logs
    environment:
      - TZ=America/Denver
      - MATOMO_DATABASE_HOST=mariadb
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=test
      - MATOMO_DATABASE_DBNAME=matomo
    ports:
      - 7000:80

volumes:
  db:
  matomo:

networks:
  default:
    external:
      name: playground-network          