version: "2.2"

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always
    environment:
      - TZ=America/Denver
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=test
      - MATOMO_DATABASE_DBNAME=matomo
    command: --max_allowed_packet=64M

  app:
    image: matomo:fpm
    container_name: matomo
    restart: always
    environment:
      - TZ=America/Denver
      - MATOMO_DATABASE_HOST=mariadb
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=test
      - MATOMO_DATABASE_DBNAME=matomo
    volumes:
      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs
    depends_on:
      - mariadb
      
  web:
    image: nginx:latest
    container_name: nginx-matomo
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    ports:
      - 7000:80
    depends_on:
      - mariadb
      - app

networks:
  default:
    external:
      name: playground-network          